import { makeStyles, shorthands } from '@griffel/react'
import { tokens } from '../../../common/styles/tokens'

export const useCanvasStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#FFFFFF',
    ...shorthands.borderRadius('20px'),
    boxShadow: tokens.shadowCard,
    ...shorthands.overflow('hidden'),
    fontFamily: tokens.fontFamily,
  },
  header: {
    ...shorthands.padding('14px', '24px'),
    ...shorthands.borderBottom('1px', 'solid', tokens.borderDivider),
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  titleBlock: {
    display: 'flex',
    flexDirection: 'column',
  },
  title: {
    fontSize: '16px',
    fontWeight: 700,
    margin: 0,
    color: tokens.colorTextDark,
  },
  metaBadge: {
    fontSize: '12px',
    color: tokens.colorTextSub,
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  workerStatusTag: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    backgroundColor: '#EFFFF6',
    color: tokens.colorMintIcon,
    ...shorthands.border('1px', 'solid', '#D3FFE7'),
    ...shorthands.padding('4px', '10px'),
    ...shorthands.borderRadius('6px'),
    fontWeight: 600,
  },
  workerDot: {
    width: '6px',
    height: '6px',
    ...shorthands.borderRadius('50%'),
    backgroundColor: tokens.colorMintIcon,
  },
  mainContent: {
    display: 'flex',
    flexGrow: 1,
    ...shorthands.overflow('hidden'),
  },
  canvasViewport: {
    flexGrow: 1,
    backgroundColor: '#E8ECF4',
    overflowY: 'auto',
    overflowX: 'auto',
    ...shorthands.padding('30px'),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  canvasSheet: {
    width: '780px',
    minHeight: '1050px',
    backgroundColor: '#FFFFFF',
    color: '#1a202c',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.15)',
    position: 'relative',
    transitionProperty: 'transform',
    transitionDuration: '0.1s',
  },
  sheetContent: {
    ...shorthands.padding('48px', '56px'),
    position: 'relative',
  },
  watermark: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%) rotate(-35deg)',
    fontSize: '2.5rem',
    fontWeight: 800,
    color: 'rgba(89, 50, 234, 0.04)',
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
  },
  sheetHeader: {
    ...shorthands.borderBottom('2px', 'solid', tokens.colorPrimary),
    paddingBottom: '12px',
    marginBottom: '24px',
  },
  sheetHeading: {
    fontSize: '1.2rem',
    fontWeight: 700,
    color: '#0f172a',
    margin: 0,
  },
  sheetSub: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '4px',
    margin: 0,
  },
  sheetBody: {
    fontSize: '0.85rem',
    lineHeight: 1.7,
    color: '#334155',
  },
  articleTitle: {
    fontSize: '0.95rem',
    fontWeight: 700,
    color: '#0f172a',
    marginTop: '18px',
    marginBottom: '6px',
  },
  sheetTable: {
    marginTop: '24px',
    ...shorthands.border('1px', 'solid', '#cbd5e1'),
    ...shorthands.borderRadius('4px'),
    ...shorthands.overflow('hidden'),
  },
  sheetTr: {
    display: 'grid',
    gridTemplateColumns: '1.5fr 1fr 2fr',
    ...shorthands.padding('8px', '12px'),
    ...shorthands.borderBottom('1px', 'solid', '#e2e8f0'),
    fontSize: '0.8rem',
  },
  sheetFooter: {
    marginTop: '50px',
    ...shorthands.borderTop('1px', 'solid', '#cbd5e1'),
    paddingTop: '12px',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.75rem',
    color: '#94a3b8',
  },
  commentsSidebar: {
    width: '280px',
    backgroundColor: '#FFFFFF',
    ...shorthands.borderLeft('1px', 'solid', tokens.borderDivider),
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  commentsHeader: {
    ...shorthands.padding('14px', '18px'),
    ...shorthands.borderBottom('1px', 'solid', tokens.borderDivider),
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentsTitle: {
    fontSize: '14px',
    fontWeight: 700,
    margin: 0,
  },
  commentsList: {
    flexGrow: 1,
    overflowY: 'auto',
    ...shorthands.padding('14px'),
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  commentCard: {
    backgroundColor: '#F9FBFF',
    ...shorthands.border('1px', 'solid', '#E8ECF4'),
    ...shorthands.borderRadius('8px'),
    ...shorthands.padding('10px'),
    cursor: 'pointer',
  },
  commentCardActive: {
    ...shorthands.borderColor(tokens.colorPrimary),
  },
  commentHead: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  commentAuthor: {
    fontSize: '12px',
    fontWeight: 700,
    color: tokens.colorPrimary,
  },
  commentTime: {
    fontSize: '10px',
    color: tokens.colorTextSub,
  },
  commentBody: {
    fontSize: '12px',
    lineHeight: 1.4,
    margin: 0,
  },
  commentForm: {
    ...shorthands.padding('12px'),
    ...shorthands.borderTop('1px', 'solid', tokens.borderDivider),
    backgroundColor: '#F9FBFF',
  },
  loadingContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '400px',
    width: '100%',
  },
})
