import { makeStyles, shorthands } from '@griffel/react'
import { tokens } from '../../common/styles/tokens'

export const useSidebarStyles = makeStyles({
  sidebar: {
    width: '250px',
    minWidth: '250px',
    backgroundColor: tokens.colorCardBg,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    boxShadow: tokens.shadowCard,
    zIndex: 20,
    paddingBottom: '10px',
    fontFamily: tokens.fontFamily,
    height: '100vh',
  },
  topSection: {
    ...shorthands.padding('28px', '24px', '0', '24px'),
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '40px',
  },
  logoIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoBrandText: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '4px',
  },
  logoTitle: {
    fontSize: '20px',
    fontWeight: 700,
    color: tokens.colorTextDark,
    letterSpacing: '-0.5px',
  },
  logoVersion: {
    fontSize: '10px',
    color: tokens.colorTextSub,
    fontWeight: 500,
  },
  navMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  navBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    width: '100%',
    ...shorthands.padding('12px', '14px'),
    ...shorthands.borderRadius(tokens.borderRadiusSm),
    backgroundColor: 'transparent',
    ...shorthands.border('none'),
    color: tokens.colorTextGray,
    fontSize: '14px',
    fontFamily: tokens.fontFamily,
    fontWeight: 500,
    cursor: 'pointer',
    textAlign: 'left',
    transitionProperty: 'all',
    transitionDuration: '0.15s',
    transitionTimingFunction: 'ease',
    ':hover': {
      color: tokens.colorTextDark,
      backgroundColor: '#F9FBFF',
    },
  },
  navBtnActive: {
    backgroundColor: `${tokens.colorPrimary} !important`,
    color: '#FFFFFF !important',
    boxShadow: '0px 4px 10px rgba(89, 50, 234, 0.3)',
  },
  navIcon: {
    flexShrink: 0,
  },
  navText: {
    flexGrow: 1,
  },
  navChevron: {
    fontSize: '18px',
    fontWeight: 600,
    opacity: 0.8,
    marginLeft: 'auto',
  },
  bottomSection: {
    ...shorthands.padding('0', '20px'),
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  proUpgradeCard: {
    background: 'linear-gradient(107.91deg, #EAABF0 7.37%, #4623E9 95.19%)',
    ...shorthands.borderRadius('20px'),
    ...shorthands.padding('22px', '18px'),
    textAlign: 'center',
    color: '#FFFFFF',
  },
  proTitle: {
    fontSize: '13px',
    fontWeight: 600,
    lineHeight: 1.4,
    marginBottom: '14px',
    margin: 0,
  },
  proBtn: {
    width: '100%',
    ...shorthands.padding('10px', '0'),
    backgroundColor: '#FFFFFF',
    color: '#4925E9',
    ...shorthands.border('none'),
    ...shorthands.borderRadius('20px'),
    fontSize: '12px',
    fontWeight: 700,
    fontFamily: tokens.fontFamily,
    cursor: 'pointer',
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1)',
    transitionProperty: 'transform',
    transitionDuration: '0.15s',
    marginTop: '14px',
    ':hover': {
      transform: 'translateY(-1px)',
    },
  },
  userFooter: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    ...shorthands.padding('8px', '4px'),
    cursor: 'pointer',
  },
  userImg: {
    width: '42px',
    height: '42px',
    ...shorthands.borderRadius('50%'),
    objectFit: 'cover',
  },
  userText: {
    display: 'flex',
    flexDirection: 'column',
  },
  userName: {
    fontSize: '14px',
    color: tokens.colorTextDark,
    fontWeight: 700,
    lineHeight: 1.2,
  },
  userRole: {
    fontSize: '12px',
    color: tokens.colorTextSub,
    lineHeight: 1.2,
  },
  userDropdownArrow: {
    marginLeft: 'auto',
    color: tokens.colorTextSub,
    fontSize: '12px',
  },
})
